AWSTemplateFormatVersion: '2010-09-09'
Description: Alexa Rain Drop Function 1.0.0

Resources:
  AlexaRainDropLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: BUCKET_NAME
        S3Key: raindrop.zip
      Description: Alexa Rain Drop Function
      FunctionName: AlexaRainDrop
      Handler: lambda_function.lambda_handler
      Role: !GetAtt AlexaRainDropIamRole.Arn 
      Runtime: python2.7
      Timeout: 3
    DependsOn: AlexaRainDropIamRole

  AlexaSkillFunctionPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: AlexaRainDrop
      Action: lambda:InvokeFunction
      Principal: alexa-appkit.amazon.com
    DependsOn: AlexaRainDropLambdaFunction

Outputs:
  AlexaRainDropIamRoleArn:
    Description: Alexa Rain Drop IAM role ARN
    Value:
      !GetAtt AlexaRainDropIamRole.Arn
    Export:
      Name: AlexaRainDropIamRoleArn
  AlexaRainDropFunctionArn:
    Description: Alexa Rain Drop Function Arn
    Value:
      !GetAtt AlexaRainDropLambdaFunction.Arn
    Export:
      Name: AlexaRainDropFunctionName
