AWSTemplateFormatVersion: '2010-09-09'
Description: Alexa Rain Drop Function 1.0.0

Resources:
  AlexaRainDropLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: !ImportValue AlexaRainDropS3Bucket
        S3Key: raindrop.zip
      Description: Alexa Rain Drop Function
      FunctionName: AlexaRainDrop
      Handler: raindrop.lambda_handler
      Role: !ImportValue AlexaRainDropIamRoleArn
      Runtime: python2.7
      Timeout: 3

  AlexaBadBoujeeLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: !ImportValue AlexaRainDropS3Bucket
        S3Key: badboujee.zip
      Description: Alexa Bad Boujee Function
      FunctionName: AlexaBadBoujee
      Handler: badboujee.lambda_handler
      Role: !ImportValue AlexaRainDropIamRoleArn
      Runtime: python2.7
      Timeout: 3

  RainDropSkillFunctionPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: AlexaRainDrop
      Action: lambda:InvokeFunction
      Principal: alexa-appkit.amazon.com
    DependsOn: AlexaRainDropLambdaFunction

  BadBoujeeSkillFunctionPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: AlexaBadBoujee
      Action: lambda:InvokeFunction
      Principal: alexa-appkit.amazon.com
    DependsOn: AlexaBadBoujeeLambdaFunction

Outputs:
  AlexaRainDropFunctionArn:
    Description: Alexa Rain Drop Function Arn
    Value:
      !GetAtt AlexaRainDropLambdaFunction.Arn
    Export:
      Name: AlexaRainDropFunctionName
  AlexaBadBoujeeFunctionArn:
    Description: Alexa BadBoujee Function Arn
    Value:
      !GetAtt AlexaBadBoujeeLambdaFunction.Arn
    Export:
      Name: AlexaBadBoujeeFunctionName
